<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cramirez
 * Date: Wed, 13 Apr 2016 15:02:39 -0700
 */

$conf['title'] = 'Natalia Garcia shoes';
$conf['lang'] = 'es';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
